server:
  port:
    8082

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?verifyServerCertificate=false&useSSL=true
    username: asd
    password: asdf
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto:       
  data:
    jpa.repositories.enabled: true 
